### ISSUE TITLE
Tab autocompletion doesn't seem to be working in iTerm 2/Terminal

### ISSUE THREAD

**Issue by alexwlchan** [mikaelmello/inquire#66]
### Describe the bug

I'm trying the text suggestions in 0.3.0-alpha.2 in a terminal on macOS; it tells me I can use "tab to auto-complete", but it doesn't seem to work.

### Reproduction project

This is my `Cargo.toml`:

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.3.0-alpha.2"
```

and this is my `main.rs`, which is a simplified version of [`examples/text_options.rs`](https://github.com/mikaelmello/inquire/blob/84b09bd07203a9a22481053043ef8cfd8d48db9e/examples/text_options.rs):

```rust
use inquire::{error::CustomUserError, Text};

fn suggester(val: &str) -> Result<Vec<String>, CustomUserError> {
    let suggestions = ["andrew", "charles", "christopher"];

    Ok(suggestions
        .iter()
        .filter(|s| s.contains(&val))
        .map(|s| String::from(*s))
        .collect())
}

fn main() {
    let answer = Text::new("What's your name?")
        .with_suggester(&suggester)
        .prompt()
        .unwrap();

    println!("Hello {}", answer);
}
```

### Expected/actual behaviour

If I run the code, I get a prompt with three suggestions:

<img width="843" alt="Screenshot 2022-08-16 at 20 43 45" src="https://user-images.githubusercontent.com/301220/184969873-c6693b28-8ef8-4641-b350-352e449c6b26.png">

If I then type `cha` for `charles`, my selection reduces to a single item:

<img width="843" alt="Screenshot 2022-08-16 at 20 45 33" src="https://user-images.githubusercontent.com/301220/184970597-240b6a5e-7795-4ccf-bdca-eea99c0382c4.png">

At this point, I expect that pressing `tab` will complete to `charles`, but as far as I can tell nothing happens.

### Desktop

 - OS: macOS Catalina 10.15.7
 - Terminal: iTerm 2 3.4.16 and Terminal 2.10; I get the same behaviour in both
 - Version: 0.3.0-alpha.2

### Additional context

I can reproduce this error if I swap out the back-ends, in particular either of the following lines in my `Cargo.toml` have the same behaviour:

```toml
inquire = { version = "0.3.0-alpha.2", features = ["console"] }

inquire = { version = "0.3.0-alpha.2", features = ["termion"] }
```

**Comment by alexwlchan** [comment]
I get similar behaviour in 0.2.1.

Cargo.toml:

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.2.1"
```

main.rs:

```rust
use inquire::Text;

fn suggester(val: &str) -> Vec<String> {
    let suggestions = ["andrew", "charles", "christopher"];

    suggestions
        .iter()
        .filter(|s| s.contains(&val))
        .map(|s| String::from(*s))
        .collect()
}

fn main() {
    let answer = Text::new("What's your name?")
        .with_suggester(&suggester)
        .prompt()
        .unwrap();

    println!("Hello {}", answer);
}
```

I was trying the alpha version because I want to play with the shiny autocomplete stuff! :D
